---
title: "20201021-p8133_probset5_jsg2145"
author: "Jared Garfinkel"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = FALSE,
	warning = FALSE,
	message = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
data = read_delim("./data/data.txt", delim = " ", col_names = FALSE) %>% 
  select(-X1) %>% 
  pivot_longer(cols = X2:X11, names_to = "list") %>% 
  select(value)
data %>% 
  pull(value) %>% 
  hist()
```

```{r}
p = c(.02, .04, .10, .25, .50)
```


```{r, eval = FALSE}
res = vector(mode = "list", length = 250)
i = NULL
j = NULL
ntox = NULL
for (i in 1:5) {
  res = cbind(0, 1, 0)
  ntox = 0
  j = 1
  while (ntox < 1 && j < 250) {
    for (j in 1:3){
      if_else(pull(data, value)[[j]] < p[[i]], (ntox = ntox + 1), NULL)
      res = rbind(res, cbind(ntox, i, j))
    }
  }
  while (ntox == 1 && j < 250) {
    for (j in 3*(j-1)+1:(3*(j-1)+3)){
      if_else(pull(data, value)[[j]] < p[[i]], (ntox = ntox + 1), (j = j + 1))
      res = rbind(res, cbind(ntox, i, j))
    }
  }
  return(res)
}
  return(res)
}
  return(res)
}
      }
  }
    # res = rbind(res, cbind(ntox, i, j))
  }
}
      # res = rbind(res, cbind(ntox, i, j))
    # if_else(pull(data, value)[[j]] < p[[i]], (ntox = ntox + 1), NULL)
    # res = rbind(res, cbind(ntox, i, j))
    # j = j + 1
    # if_else(pull(data, value)[[j]] < p[[i]], (ntox = ntox + 1), NULL)
    # res = rbind(res, cbind(ntox, i, j))
    # i = i + 1
    # j = j + 1
    }
  }
  return(res)
}
  while(ntox == 1 && j < 250) {
    for (j in j:j+2)
    if_else(pull(data, value)[[j]] < p[[i]], (ntox = ntox + 1), NULL)
    res = rbind(res, cbind(ntox, i, j))
  }
  # while(ntox == 1 && j < 250){
  #   if_else()
  # }
  
  
    # if_else(pull(data, value)[[j]] <=  p[[i]], (ntox = ntox + 1), (j = j + 1))
  # res = rbind(res, cbind(ntox, i, j))
  # if_else(pull(data, value)[[j]] <= p[[i]], (ntox = ntox + 1), j = j + 1)
  # res = rbind(res, cbind(ntox, i,))

  # }
  return(res)
}
```

```{r, eval = FALSE}
pull(data, value)[[2]] < p[[1]]
```

```{r, eval = FALSE}
res = vector(mode = "list", length = 250)
ntox = 0
i = 1
j = 1
# for (i in 1:5) {
while (ntox < 2 && i %in% c(1:5) && j %in% 1:83) {
  # for (j in 1:83) {
  for (k in (3*(j-1)+1):(3*(j-1)+3)) {
    ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
    res = rbind(res, cbind(ntox, i, k, j))
  }
  if(ntox == 1) {
    for (k in (3*j+1):(3*j+3)) {
      ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
      res = rbind(res, cbind(ntox, i, k, j))
    }
    j = j + 1
  }
  res = rbind(res, cbind(ntox, i, k, j))
  ntox = 0
  i = i + 1
  j = j + 1
  return(res)
}
# }
# }
# }
  # return(res)
# }
p
data
res
```
```{r, echo = TRUE}
res = vector(mode = "list", length = 250)
ntox = 0
i = 1
j = 1
while (ntox < 2 && i %in% c(1:5) && j %in% 1:83) {
  for (k in (3*(j-1)+1):(3*(j-1)+3)) {
    ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
    res = rbind(res, cbind(ntox, i, k, j))
  }
  if(ntox == 1) {
    for (k in (3*j+1):(3*j+3)) {
      ntox = if_else(pull(data, value)[[k]] < p[[i]], (ntox + 1), ntox)
      res = rbind(res, cbind(ntox, i, k, j))
    }
    j = j + 1
  }
  ntox = 0
  i = i + 1
  j = j + 1
}
res
```



```{r, eval = FALSE}
#     ntox = if_else(ntox == 1,
#             (for (l in (3*j+1):(3*j+3)) {
#               ntox = if_else(pull(data, value)[[l]] < p[[i]], (ntox + 1), ntox)
#               res = rbind(res, cbind(ntox, i, k = l))
#             }),
#             ntox)
#   }
#   ntox = 0
#   return(res)
# }
    ntox = 0
  }
  return(res)
}
    # while (ntox == 1) {
    #   for (l in (3*j+1):(3*j+3)) {
    #     ntox = if_else(pull(data, value)[[l]] < p[[i]], (ntox + 1), ntox)
    #     res = rbind(res, cbind(ntox, i, l))
    #   }
    # }
    }
    return(tail(res))
  }
  return(tail(res))
}
    
#       }
#     }
#     ntox = 0
#     return(res)
# }
#   return(res)
# }
#   }
#   return(res)
# }
# 
#   while (ntox == 1 && j < 250) {
#     k = j
#     for (j in k:k+2){
#       if_else(pull(data, value)[[j]] < p[[i]], (ntox = ntox + 1), (ntox = ntox))
#       res = rbind(res, cbind(ntox, i, j))
#       k = k + 1
#     }
#   }
#   return(res)
# }
```

```{r, eval = FALSE}
ntox = if_else(pull(data, value)[[1]] < p[[1]], (ntox + 1), ntox)
ntox = if_else(pull(data, value)[[2]] < p[[1]], (ntox + 1), ntox)
ntox = if_else(pull(data, value)[[3]] < p[[1]], (ntox + 1), ntox)
ntox = if_else(pull(data, value)[[4]] < 1, (ntox + 1), ntox)
ntox
ntox = 0
ntox
# data
```

